<a href="https://colab.research.google.com/github/ZohanaZuthi/1st-project/blob/main/Data_Processing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Importing Libraries**

In [2]:
# importing the libraries
# In machine learning there are three kind of libraries that will be used
#  for array numpy , for ploting pyplot from matplotlib, for matrics pandas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## **Reading the data file**

at first we need to read the data file. then define the independent and the dependent variable. Here in the data.csv file , we will take the first three column as independent variable and the last column will be our dependent or prediction column.

By using iloc function we locate the row:column range , here : means all the values will be included. then the next parameters defines the independent/dependent column, In x the last column will be excluded thats why :-1. But in y case only the last column will be included, that's why just -1

In [4]:
dataset=pd.read_csv('Data.csv')

In [5]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [8]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [10]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### **Taking care of missing data**

In this case we will use sicit learn. with this library we will fill all the missing valuess with average value.

In [13]:
from sklearn.impute import SimpleImputer
# the instance of the class
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
# fit method will calculate the mean and also look for missing values
# fit expects only numerical arguments not text
# transform will replace the missing
imputer.fit(x[:,1:3])
# python excludes the last pointer after:

# transform creates new updatedd matrix
# so we need to replace the expected column with the matrices
x[:,1:3]=imputer.transform(x[:,1:3])

In [14]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## **Replacing non numerical value with binary numbers**

## **Encoding for Independent Variable**

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [17]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
# fit plus transform method
x=np.array(ct.fit_transform(x))

In [18]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## **Encoding for Dependent Variables**

For this we need label

In [22]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [23]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## **Splitting the Dataset into training and test dataset**

Feature scaling will be applied after the spliting. the future machine will expect 4 kind of data set x_train,y_train,x_test,y_test

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

random_state=1 ensures that the splitting of data into training and testing sets is reproducible. When you set a specific value (e.g., 1), it initializes the random number generator in a consistent way every time you run the code, meaning you'll get the same split each time.

In [25]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [26]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [27]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [28]:
print(y_test)

[0 1]


## **Feature Scaling**

In general there are two types of feature scaling. Normalisation and Standardisation. Standardisation always works optimally

In [33]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:, 3:]=sc.fit_transform(x_train[:, 3:])
x_test[:,3:]=sc.fit_transform(x_test[:,3:])

In [34]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578554 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057846 -0.07013167641635404]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022487 -0.307866172742979]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [35]:
print(x_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
